### PR TITLE
Fix #100 and add deployScaleFactor parameter

### LINKED ISSUE #100: Logs from openshift project are not collected
`openShiftUtils.collectLogs(project: project)` in `execSmokeTest` fails with:
```
[Pipeline] { (Collecting logs)
[Pipeline] stage
[Pipeline] { (Collect logs)
[Pipeline] sh
[Pipeline] echo
Collecting logs failed: org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
[Pipeline] }
```

@bsquizz Can you please take a look? It looks like it suddenly stopped working despite the code haven't been changed in months.

### PR DESCRIPTION
**Pull request by psegedy**
- https://github.com/RedHatInsights/insights-pipeline-lib/issues/100 openshiftUtils.collectLogs has to be run inside Node
- add deployScaleFactor parameter to scale resources of the first service set in the list

### CODE REVIEW

File: vars/execSmokeTest.groovy [hunk 1]
```diff
@@ -105,12 +105,16 @@ private def deployEnvironment(
     }
 
     // Deploy the other service sets
-    for (serviceSet in ocDeployerServiceSets.split(',')) {
+    ocDeployerServiceSets.split(',').eachWithIndex { serviceSet, i ->
         def set = serviceSet // https://jenkins.io/doc/pipeline/examples/#parallel-multiple-nodes
+        // Deploy the tested service with scaled resources and other services with default resources
```
Comment (bsquizz) [inline vars/execSmokeTest.groovy:110]: I'd prefer if we added a boolean option like `scaleFirstSetOnly` (false by default) to enable this behavior because otherwise we're changing how this has worked in the past and I'm not sure if it is going to impact anyone

File: vars/execSmokeTest.groovy [hunk 2]
```diff
@@ -181,15 +179,26 @@ private def runPipeline(
...
-            ocDeployerServiceSets, buildScaleFactor, parallelBuild, options['cloud']
+            ocDeployerServiceSets, buildScaleFactor, deployScaleFactor,
+            parallelBuild, parameters
         )
 
         results = pipelineUtils.runParallel(iqeUtils.prepareStages(options, appConfigs))
 
-        stage("Collecting logs") {
-            openShiftUtils.collectLogs(project: project)
+        openShiftUtils.withNode(parameters) {
```
Comment (bsquizz) [inline vars/execSmokeTest.groovy:198]: I would do:

```
if (results['failed']) {
    <collect logs>
}
```

Since spinning up a new node can take ~1-2min (assuming everything is working OK on OpenShift) -- I think there's likely no need to spin up the node to collect logs if all the tests passed

**Review by bsquizz — CHANGES_REQUESTED** [review]

File: vars/execSmokeTest.groovy (hunk 1 above)
Comment (psegedy) [reply vars/execSmokeTest.groovy]: added `scaleFirstSetOnly`

File: vars/execSmokeTest.groovy (hunk 2 above)
Comment (psegedy) [reply vars/execSmokeTest.groovy]: done

**Review by bsquizz — APPROVED** [review]
